// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240804203009_HastaDegerlendirmee")]
    partial class HastaDegerlendirmee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.AgriHastaBakimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<int>("HemsireId")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Saat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("HemsireId");

                    b.ToTable("AgriHastaBakimPlanlari");
                });

            modelBuilder.Entity("Entities.Concrete.Amac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("Amaclar");
                });

            modelBuilder.Entity("Entities.Concrete.CheckboxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("CheckboxItems");
                });

            modelBuilder.Entity("Entities.Concrete.Degerlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DegerlendirmeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarih")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("Entities.Concrete.Girisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("Girisimler");
                });

            modelBuilder.Entity("Entities.Concrete.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HemsireTanisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("Entities.Concrete.Hemsire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hemsireler");
                });

            modelBuilder.Entity("Entities.Concrete.Neden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("Nedenler");
                });

            modelBuilder.Entity("Entities.Concrete.Sonuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("Sonuclar");
                });

            modelBuilder.Entity("Entities.Concrete.TaniOlculeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriHastaBakimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriHastaBakimPlaniId");

                    b.ToTable("TaniOlculeriList");
                });

            modelBuilder.Entity("Entities.Concrete.AgriHastaBakimPlani", b =>
                {
                    b.HasOne("Entities.Concrete.Hasta", "Hasta")
                        .WithMany("AgriHastaBakimPlanlari")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Hemsire", "Hemsire")
                        .WithMany("AgriHastaBakimPlanlari")
                        .HasForeignKey("HemsireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Hemsire");
                });

            modelBuilder.Entity("Entities.Concrete.Amac", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", "AgriHastaBakimPlani")
                        .WithMany("Amaclar")
                        .HasForeignKey("AgriHastaBakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriHastaBakimPlani");
                });

            modelBuilder.Entity("Entities.Concrete.CheckboxItem", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", null)
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("AgriHastaBakimPlaniId");
                });

            modelBuilder.Entity("Entities.Concrete.Degerlendirme", b =>
                {
                    b.HasOne("Entities.Concrete.Hasta", "Hasta")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("Entities.Concrete.Girisim", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", "AgriHastaBakimPlani")
                        .WithMany("Girisimler")
                        .HasForeignKey("AgriHastaBakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriHastaBakimPlani");
                });

            modelBuilder.Entity("Entities.Concrete.Neden", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", "AgriHastaBakimPlani")
                        .WithMany("Nedenler")
                        .HasForeignKey("AgriHastaBakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriHastaBakimPlani");
                });

            modelBuilder.Entity("Entities.Concrete.Sonuc", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", "AgriHastaBakimPlani")
                        .WithMany("Sonuclar")
                        .HasForeignKey("AgriHastaBakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriHastaBakimPlani");
                });

            modelBuilder.Entity("Entities.Concrete.TaniOlculeri", b =>
                {
                    b.HasOne("Entities.Concrete.AgriHastaBakimPlani", "AgriHastaBakimPlani")
                        .WithMany("TaniOlculeriList")
                        .HasForeignKey("AgriHastaBakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriHastaBakimPlani");
                });

            modelBuilder.Entity("Entities.Concrete.AgriHastaBakimPlani", b =>
                {
                    b.Navigation("Amaclar");

                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Girisimler");

                    b.Navigation("Nedenler");

                    b.Navigation("Sonuclar");

                    b.Navigation("TaniOlculeriList");
                });

            modelBuilder.Entity("Entities.Concrete.Hasta", b =>
                {
                    b.Navigation("AgriHastaBakimPlanlari");

                    b.Navigation("Degerlendirmeler");
                });

            modelBuilder.Entity("Entities.Concrete.Hemsire", b =>
                {
                    b.Navigation("AgriHastaBakimPlanlari");
                });
#pragma warning restore 612, 618
        }
    }
}
